#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-env
Version  : 0.2.1
Release  : 1
URL      : https://pecl.php.net//get/env-0.2.1.tgz
Source0  : https://pecl.php.net//get/env-0.2.1.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: php-env-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
# env
[![Build Status](https://travis-ci.org/beberlei/env.svg)](https://travis-ci.org/beberlei/env)

%package lib
Summary: lib components for the php-env package.
Group: Libraries

%description lib
lib components for the php-env package.


%prep
%setup -q -n env-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/env.so
